do nothing
[Modelarts Service Log]user: uid=1101(work) gid=1101(work) groups=1101(work),1000(HwHiAiUser)
[Modelarts Service Log]pwd: /home/work
[Modelarts Service Log]app_url: s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/code/
[Modelarts Service Log]boot_file: code/train.py
[Modelarts Service Log]log_url: /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[Modelarts Service Log]command: code/train.py --data_url=s3://pcn/pcn_dataset/pcn/ --train_url=s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/output/V0058/
[Modelarts Service Log]local_code_dir: 
[Modelarts Service Log]Training start at 2021-07-18-00:19:25
[Modelarts Service Log][modelarts_create_log] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[Modelarts Service Log]handle inputs of training job
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
[ModelArts Service Log][INFO][2021/07/18 00:19:26]: env MA_INPUTS is not found, skip the inputs handler
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
[ModelArts Service Log]2021-07-18 00:19:26,798 - modelarts-downloader.py[line:620] - INFO: Main: modelarts-downloader starting with Namespace(dst='./', recursive=True, skip_creating_dir=False, src='s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/code/', trace=False, type='common', verbose=False)
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[Modelarts Service Log][INFO] exec pip install
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
Collecting pyarrow==0.10.0 (from -r /home/work/user-job-dir/code/pip-requirements.txt (line 1))
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/c0/a0/f7e9dfd8988d94f4952f9b50eb04e14a80fbe39218520725aab53daab57c/pyarrow-0.10.0.tar.gz (2.1MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/ma/python3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-99k8d28h/pyarrow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-99k8d28h/pyarrow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-99k8d28h/pyarrow/
    Complete output (29 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-99k8d28h/pyarrow/setup.py", line 545, in <module>
        url="https://arrow.apache.org/"
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/ma/python3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 446, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/ma/python3.7/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 734, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-99k8d28h/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/integration.py", line 24, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-install-99k8d28h/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-install-99k8d28h/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 119, in _do_parse
        parse_result = _call_entrypoint_fn(config.absolute_root, config, config.parse)
      File "/tmp/pip-install-99k8d28h/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn
        return fn(root)
      File "/tmp/pip-install-99k8d28h/pyarrow/setup.py", line 496, in parse_version
        version = setuptools_scm.git.parse(root, describe)
      File "/tmp/pip-install-99k8d28h/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/git.py", line 115, in parse
        require_command("git")
      File "/tmp/pip-install-99k8d28h/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/utils.py", line 142, in require_command
        raise OSError("%r was not found" % name)
    OSError: 'git' was not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
/home/work/user-job-dir
[ModelArts Service Log]modelarts-pipe: total length: 3314
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
[Modelarts Service Log]2021-07-18 00:20:32,881 - WARNING - stdout log /var/log/batch-task/job567a37af/job-ma-pcn-npu-202106101/stdout.log is not found
[Modelarts Service Log]2021-07-18 00:20:32,889 - INFO - you are advised to use ASCEND_DEVICE_ID env instead of DEVICE_ID, as the DEVICE_ID env will be discarded in later versions
[Modelarts Service Log]2021-07-18 00:20:32,889 - INFO - particularly, ${ASCEND_DEVICE_ID} == ${DEVICE_ID}, it's the logical device id
[Modelarts Service Log]2021-07-18 00:20:32,889 - INFO - Davinci training command
[Modelarts Service Log]2021-07-18 00:20:32,889 - INFO - ['/usr/bin/python', '/home/work/user-job-dir/code/train.py', '--data_url=s3://pcn/pcn_dataset/pcn/', '--train_url=s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/output/V0058/']
[Modelarts Service Log]2021-07-18 00:20:32,889 - INFO - Wait for Rank table file ready
[Modelarts Service Log]2021-07-18 00:20:32,889 - INFO - Rank table file (K8S generated) is ready for read
[Modelarts Service Log]2021-07-18 00:20:32,890 - INFO - 
{
    "status": "completed",
    "group_count": "1",
    "group_list": [
        {
            "group_name": "job-ma-pcn-npu-202106101",
            "device_count": "1",
            "instance_count": "1",
            "instance_list": [
                {
                    "pod_name": "job567a37af-job-ma-pcn-npu-202106101-0",
                    "server_id": "192.168.0.128",
                    "devices": [
                        {
                            "device_id": "0",
                            "device_ip": "192.1.112.92"
                        }
                    ]
                }
            ]
        }
    ]
}
[Modelarts Service Log]2021-07-18 00:20:32,890 - INFO - Rank table file (C7x)
[Modelarts Service Log]2021-07-18 00:20:32,890 - INFO - 
{
    "status": "completed",
    "version": "1.0",
    "server_count": "1",
    "server_list": [
        {
            "server_id": "192.168.0.128",
            "device": [
                {
                    "device_id": "0",
                    "device_ip": "192.1.112.92",
                    "rank_id": "0"
                }
            ]
        }
    ]
}
[Modelarts Service Log]2021-07-18 00:20:32,891 - INFO - Rank table file (C7x) is generated
[Modelarts Service Log]2021-07-18 00:20:32,891 - INFO - Current server
[Modelarts Service Log]2021-07-18 00:20:32,891 - INFO - 
{
    "server_id": "192.168.0.128",
    "device": [
        {
            "device_id": "0",
            "device_ip": "192.1.112.92",
            "rank_id": "0"
        }
    ]
}
[Modelarts Service Log]2021-07-18 00:20:32,891 - INFO - bootstrap proc-rank-0-device-0
[Modelarts Service Log]2021-07-18 00:20:32,900 - INFO - proc-rank-0-device-0 (pid: 124)
Uninstalling enum34-1.1.10:
  Successfully uninstalled enum34-1.1.10
Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
Collecting lmdb==0.97
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/9f/8f/37cc080deb867305bf2d3ec4639e33b981d0def8d78949454a4654ca16bf/lmdb-0.97.tar.gz (869kB)
Building wheels for collected packages: lmdb
  Building wheel for lmdb (setup.py): started
  Created wheel for lmdb: filename=lmdb-0.97-cp37-cp37m-linux_aarch64.whl size=270186 sha256=126076144036b8c28588a2747217dfae0fcdac35d2b80fa9d819135c5b9d8614
  Stored in directory: /home/work/.cache/pip/wheels/9a/ce/6a/f9fda9565e0fa6a5e96a4c312a6171baf87b91bba0401846c4
Successfully built lmdb
Installing collected packages: lmdb
Successfully installed lmdb-0.97
Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
Collecting pyarrow==0.10.0
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/c0/a0/f7e9dfd8988d94f4952f9b50eb04e14a80fbe39218520725aab53daab57c/pyarrow-0.10.0.tar.gz (2.1MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/ma/python3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i5aqkz8q/pyarrow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i5aqkz8q/pyarrow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-i5aqkz8q/pyarrow/
    Complete output (29 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i5aqkz8q/pyarrow/setup.py", line 545, in <module>
        url="https://arrow.apache.org/"
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/ma/python3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 446, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/ma/python3.7/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 734, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-i5aqkz8q/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/integration.py", line 24, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-install-i5aqkz8q/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-install-i5aqkz8q/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 119, in _do_parse
        parse_result = _call_entrypoint_fn(config.absolute_root, config, config.parse)
      File "/tmp/pip-install-i5aqkz8q/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn
        return fn(root)
      File "/tmp/pip-install-i5aqkz8q/pyarrow/setup.py", line 496, in parse_version
        version = setuptools_scm.git.parse(root, describe)
      File "/tmp/pip-install-i5aqkz8q/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/git.py", line 115, in parse
        require_command("git")
      File "/tmp/pip-install-i5aqkz8q/pyarrow/.eggs/setuptools_scm-6.0.1-py3.7.egg/setuptools_scm/utils.py", line 142, in require_command
        raise OSError("%r was not found" % name)
    OSError: 'git' was not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
Collecting tensorpack
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/f9/8c/63e5f5a4a04dea36b75850f9daa885ccbfad64bec1fae0ee4ca9f31b3eaa/tensorpack-0.11-py2.py3-none-any.whl (296kB)
Requirement already satisfied: tqdm>4.29.0 in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack) (4.46.1)
Requirement already satisfied: six in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack) (1.15.0)
Requirement already satisfied: numpy>=1.14 in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack) (1.17.5)
Collecting pyzmq>=16 (from tensorpack)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/a3/7a/561526861908d366ddc2764933a6090078654b0f2ff20c3c180dd5851554/pyzmq-22.0.3.tar.gz (1.2MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting msgpack-numpy>=0.4.4.2 (from tensorpack)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/19/05/05b8d7c69c6abb36a34325cc3150089bdafc359f0a81fb998d93c5d5c737/msgpack_numpy-0.4.7.1-py2.py3-none-any.whl
Requirement already satisfied: termcolor>=1.1 in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack) (1.1.0)
Requirement already satisfied: psutil>=5 in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack) (5.7.0)
Collecting msgpack>=0.5.2 (from tensorpack)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/59/04/87fc6708659c2ed3b0b6d4954f270b6e931def707b227c4554f99bd5401e/msgpack-1.0.2.tar.gz (123kB)
Collecting tabulate>=0.7.7 (from tensorpack)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/ca/80/7c0cad11bd99985cfe7c09427ee0b4f9bd6b048bd13d4ffb32c6db237dfb/tabulate-0.8.9-py3-none-any.whl
Building wheels for collected packages: pyzmq
  Building wheel for pyzmq (PEP 517): started
  Building wheel for pyzmq (PEP 517): still running...
  Building wheel for pyzmq (PEP 517): still running...
  Building wheel for pyzmq (PEP 517): finished with status 'done'
  Created wheel for pyzmq: filename=pyzmq-22.0.3-cp37-cp37m-linux_aarch64.whl size=6042599 sha256=f64b593c6255ec3f6e96abaf0ba988395b1c550045811c263ead9e53958dd8f3
  Stored in directory: /home/work/.cache/pip/wheels/b4/9f/a7/5b8a3feaa4f90246408e8a7e3e94b7a7167654a784c4f4a6f4
Successfully built pyzmq
Building wheels for collected packages: msgpack
  Building wheel for msgpack (setup.py): started
  Building wheel for msgpack (setup.py): finished with status 'done'
  Created wheel for msgpack: filename=msgpack-1.0.2-cp37-cp37m-linux_aarch64.whl size=224455 sha256=937fdcff8779d5dcadba82ee8e459e73ce12d8bbbdb5a8b92d3e359b5c1c3264
  Stored in directory: /home/work/.cache/pip/wheels/67/89/99/8886acf4cf40672c2fe8fa2c63661973741a3b9f3d117a6fa9
Successfully built msgpack
Installing collected packages: pyzmq, msgpack, msgpack-numpy, tabulate, tensorpack
Successfully installed msgpack-1.0.2 msgpack-numpy-0.4.7.1 pyzmq-22.0.3 tabulate-0.8.9 tensorpack-0.11
WARNING:tensorflow:From /usr/local/Ascend/tfplugin/latest/tfplugin/python/site-packages/npu_bridge/estimator/npu/npu_optimizer.py:225: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
train.lmdb
WARNING:tensorflow:From /cache/user-job-dir/code/models/pcn_cd.py:45: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
WARNING:tensorflow:From /cache/user-job-dir/code/models/pcn_cd.py:45: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
WARNING:tensorflow:From /cache/user-job-dir/code/models/pcn_cd.py:45: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.
WARNING:tensorflow:From /cache/user-job-dir/code/models/pcn_cd.py:45: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.
s3://pcn/pcn_dataset/pcn/train.lmdb
Traceback (most recent call last):
  File "/home/work/user-job-dir/code/train.py", line 188, in <module>
    train(args)
  File "/home/work/user-job-dir/code/train.py", line 79, in train
    args.lmdb_train, args.batch_size, args.num_input_points, args.num_gt_points, is_training=True)
  File "/cache/user-job-dir/code/data_util.py", line 95, in lmdb_dataflow
    df = dataflow.LMDBSerializer.load(lmdb_path, shuffle=False)
  File "/usr/local/ma/python3.7/lib/python3.7/site-packages/tensorpack/dataflow/serialize.py", line 114, in load
    df = LMDBData(path, shuffle=shuffle)
  File "/usr/local/ma/python3.7/lib/python3.7/site-packages/tensorpack/dataflow/format.py", line 90, in __init__
    self._set_keys(keys)
  File "/usr/local/ma/python3.7/lib/python3.7/site-packages/tensorpack/dataflow/format.py", line 110, in _set_keys
    self.keys = loads(self.keys)
  File "/usr/local/ma/python3.7/lib/python3.7/site-packages/tensorpack/utils/serialize.py", line 93, in loads
    return pickle.loads(buf)
_pickle.UnpicklingError: invalid load key, '\xdd'.
[Modelarts Service Log]2021-07-18 00:28:21,373 - ERROR - proc-rank-0-device-0 (pid: 124) has exited with non-zero code: 1
[Modelarts Service Log]2021-07-18 00:28:21,373 - INFO - Begin destroy training processes
[Modelarts Service Log]2021-07-18 00:28:21,373 - INFO - proc-rank-0-device-0 (pid: 124) has exited
[Modelarts Service Log]2021-07-18 00:28:21,373 - INFO - End destroy training processes
[ModelArts Service Log]modelarts-pipe: total length: 13508
[Modelarts Service Log]Training end with return code: 1
[Modelarts Service Log]upload ascend-log to s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/log/ascend-log/ at 2021-07-18-00:28:21
upload_tail_log.py -l 2048 -o s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/log/ascend-log/
[Modelarts Service Log]upload ascend-log end at 2021-07-18-00:28:22
[Modelarts Service Log]Training end at 2021-07-18-00:28:22
[Modelarts Service Log]Training completed.
