do nothing
[Modelarts Service Log]user: uid=1101(work) gid=1101(work) groups=1101(work),1000(HwHiAiUser)
[Modelarts Service Log]pwd: /home/work
[Modelarts Service Log]app_url: s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/code/
[Modelarts Service Log]boot_file: code/train.py
[Modelarts Service Log]log_url: /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[Modelarts Service Log]command: code/train.py --data_url=s3://pcn/pcn_dataset/pcn/ --train_url=s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/output/V0028/
[Modelarts Service Log]local_code_dir: 
[Modelarts Service Log]Training start at 2021-07-14-22:48:36
[Modelarts Service Log][modelarts_create_log] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[Modelarts Service Log]handle inputs of training job
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
[ModelArts Service Log][INFO][2021/07/14 22:48:36]: env MA_INPUTS is not found, skip the inputs handler
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
[ModelArts Service Log]2021-07-14 22:48:37,433 - modelarts-downloader.py[line:620] - INFO: Main: modelarts-downloader starting with Namespace(dst='./', recursive=True, skip_creating_dir=False, src='s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/code/', trace=False, type='common', verbose=False)
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
/home/work/user-job-dir
[ModelArts Service Log]modelarts-pipe: total length: 24
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/MA-pcn_npu_20210610173506-06-17-15-30.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
INFO:root:Using MoXing-v1.17.3-8aa951bc
INFO:root:Using OBS-Python-SDK-3.20.7
[Modelarts Service Log]2021-07-14 22:48:38,889 - WARNING - stdout log /var/log/batch-task/job4fe5ee9c/job-ma-pcn-npu-202106101/stdout.log is not found
[Modelarts Service Log]2021-07-14 22:48:38,898 - INFO - Ascend Driver: Version=20.2.0
[Modelarts Service Log]2021-07-14 22:48:38,899 - INFO - you are advised to use ASCEND_DEVICE_ID env instead of DEVICE_ID, as the DEVICE_ID env will be discarded in later versions
[Modelarts Service Log]2021-07-14 22:48:38,899 - INFO - particularly, ${ASCEND_DEVICE_ID} == ${DEVICE_ID}, it's the logical device id
[Modelarts Service Log]2021-07-14 22:48:38,899 - INFO - Davinci training command
[Modelarts Service Log]2021-07-14 22:48:38,899 - INFO - ['/usr/bin/python', '/home/work/user-job-dir/code/train.py', '--data_url=s3://pcn/pcn_dataset/pcn/', '--train_url=s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/output/V0028/']
[Modelarts Service Log]2021-07-14 22:48:38,899 - INFO - Wait for Rank table file ready
[Modelarts Service Log]2021-07-14 22:48:38,899 - INFO - Rank table file (K8S generated) is ready for read
[Modelarts Service Log]2021-07-14 22:48:38,900 - INFO - 
{
    "status": "completed",
    "group_count": "1",
    "group_list": [
        {
            "group_name": "job-ma-pcn-npu-202106101",
            "device_count": "1",
            "instance_count": "1",
            "instance_list": [
                {
                    "pod_name": "job4fe5ee9c-job-ma-pcn-npu-202106101-0",
                    "server_id": "192.168.0.136",
                    "devices": [
                        {
                            "device_id": "2",
                            "device_ip": "192.3.5.67"
                        }
                    ]
                }
            ]
        }
    ]
}
[Modelarts Service Log]2021-07-14 22:48:38,900 - INFO - Rank table file (C7x)
[Modelarts Service Log]2021-07-14 22:48:38,900 - INFO - 
{
    "status": "completed",
    "version": "1.0",
    "server_count": "1",
    "server_list": [
        {
            "server_id": "192.168.0.136",
            "device": [
                {
                    "device_id": "2",
                    "device_ip": "192.3.5.67",
                    "rank_id": "0"
                }
            ]
        }
    ]
}
[Modelarts Service Log]2021-07-14 22:48:38,901 - INFO - Rank table file (C7x) is generated
[Modelarts Service Log]2021-07-14 22:48:38,901 - INFO - Current server
[Modelarts Service Log]2021-07-14 22:48:38,901 - INFO - 
{
    "server_id": "192.168.0.136",
    "device": [
        {
            "device_id": "2",
            "device_ip": "192.3.5.67",
            "rank_id": "0"
        }
    ]
}
[Modelarts Service Log]2021-07-14 22:48:38,902 - INFO - bootstrap proc-rank-0-device-0
[Modelarts Service Log]2021-07-14 22:48:38,909 - INFO - proc-rank-0-device-0 (pid: 115)
Uninstalling enum34-1.1.10:
  Successfully uninstalled enum34-1.1.10
Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
Collecting lmdb
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/2f/df/3aea5279753cb8ab0c96dec43106e24f388d4179d5224f6d3e652016c095/lmdb-1.2.1.tar.gz (881kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/ma/python3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7tdv8a_t/lmdb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7tdv8a_t/lmdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-7tdv8a_t/lmdb/
    Complete output (7 lines):
    py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
    sh: /usr/bin/patch: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7tdv8a_t/lmdb/setup.py", line 119, in <module>
        raise Exception('Applying patch failed')
    Exception: Applying patch failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
Collecting tensorpack==0.8.9
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/e0/d0/8df08216e6703ddd1b9f1274a52cfa333834220b85733d36577747efa6c9/tensorpack-0.8.9-py2.py3-none-any.whl (254kB)
Collecting msgpack-numpy>=0.4.0 (from tensorpack==0.8.9)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/19/05/05b8d7c69c6abb36a34325cc3150089bdafc359f0a81fb998d93c5d5c737/msgpack_numpy-0.4.7.1-py2.py3-none-any.whl
Requirement already satisfied: tqdm>4.11.1 in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack==0.8.9) (4.46.1)
Requirement already satisfied: numpy>=1.14 in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack==0.8.9) (1.17.5)
Requirement already satisfied: six in /usr/local/ma/python3.7/lib/python3.7/site-packages (from tensorpack==0.8.9) (1.15.0)
Collecting msgpack>=0.5.2 (from tensorpack==0.8.9)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/59/04/87fc6708659c2ed3b0b6d4954f270b6e931def707b227c4554f99bd5401e/msgpack-1.0.2.tar.gz (123kB)
Collecting pyzmq>=16 (from tensorpack==0.8.9)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/a3/7a/561526861908d366ddc2764933a6090078654b0f2ff20c3c180dd5851554/pyzmq-22.0.3.tar.gz (1.2MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pyarrow>=0.9.0 (from tensorpack==0.8.9)
  Downloading http://repo.myhuaweicloud.com/repository/pypi/packages/a3/8e/43fc8348b9f4845ede3b0c02bc2a6c2f6c59b8978eec65b02daaded45a21/pyarrow-4.0.0.tar.gz (710kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/ma/python3.7/bin/python3.7 /usr/local/ma/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzi217w0t
         cwd: /tmp/pip-install-ijb6okgu/pyarrow
    Complete output (42 lines):
    Traceback (most recent call last):
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/ma/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 627, in <module>
        url='https://arrow.apache.org/'
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/ma/python3.7/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 456, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/ma/python3.7/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 807, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools_scm/integration.py", line 24, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 119, in _do_parse
        parse_result = _call_entrypoint_fn(config.absolute_root, config, config.parse)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools_scm/__init__.py", line 54, in _call_entrypoint_fn
        return fn(root)
      File "setup.py", line 546, in parse_git
        return parse(root, **kwargs)
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools_scm/git.py", line 115, in parse
        require_command("git")
      File "/tmp/pip-build-env-vbgjzv7q/overlay/lib/python3.7/site-packages/setuptools_scm/utils.py", line 142, in require_command
        raise OSError("%r was not found" % name)
    OSError: 'git' was not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/ma/python3.7/bin/python3.7 /usr/local/ma/python3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzi217w0t Check the logs for full command output.
WARNING:tensorflow:From /usr/local/Ascend/tfplugin/latest/tfplugin/python/site-packages/npu_bridge/estimator/npu/npu_optimizer.py:225: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
Traceback (most recent call last):
  File "/home/work/user-job-dir/code/train.py", line 36, in <module>
    from data_util import lmdb_dataflow, get_queued_data
  File "/cache/user-job-dir/code/data_util.py", line 29, in <module>
    from tensorpack import dataflow
ModuleNotFoundError: No module named 'tensorpack'
[ModelArts Service Log]modelarts-pipe: total length: 11520
[Modelarts Service Log]Training end with return code: 1
[Modelarts Service Log]upload ascend-log to s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/log/ascend-log/ at 2021-07-14-22:51:21
upload_tail_log.py -l 2048 -o s3://pcn/MA-pcn_npu_20210610173506-06-17-15-30/log/ascend-log/
[Modelarts Service Log]upload ascend-log end at 2021-07-14-22:51:21
[Modelarts Service Log]Training end at 2021-07-14-22:51:21
[Modelarts Service Log]Training completed.
